### ISSUE TITLE
When publishing markdown test in headings is duplicated

### ISSUE THREAD

**Issue by michaelnt** [jacebrowning/doorstop#277] opened 2017-05-31 13:03 UTC
If a heading item contains an additional paragraph of text this will be duplicated when exporting to markdown.

The html output works fine.

**Comment by guille-r** [comment] 2018-08-10 22:34
It seems there's an error in formatting the heading when exporting to markdown with command option "--no-levels all". 
HTML is also affected as the publisher export to markdown first and then to html.

to reproduce :

`$ doorstop create REQ ./reqs` 

`$ doorstop add REQ`

REQ001.yaml 
```
active: true
derived: false
level: 1.0
links: []
normative: false
ref: ''
reviewed: null
text: |
  Doorstop **shall** output heading

  And body only once.
```
then publish with :
`doorstop publish --no-levels  all REQ reqs.md`

Ouput is :
```
# Doorstop **shall** output heading

And body only once. {#REQ001 }

And body only once.
```

It should be :
```
# Doorstop **shall** output heading {#REQ001 }

And body only once.
```

**Comment by RomainTT** [comment] 2019-04-23 13:51
@jacebrowning Maybe you can close this issue since it has been fixed ? :)

**Closed** 2019-04-23 13:55 UTC
Labels: bug, help wanted
